import Vue from 'vue';

import { IconDefinition, library } from '@fortawesome/fontawesome-svg-core';
import {
	faAngleDoubleLeft,
	faAngleDown,
	faAngleRight,
	faAngleUp,
	faArrowLeft,
	faArrowRight,
	faArrowUpRightFromSquare,
	faArrowsRotate,
	faAt,
	faBook,
	faBoxOpen,
	faBug,
	faCalendar,
	faCheck,
	faChevronDown,
	faChevronUp,
	faChevronLeft,
	faChevronRight,
	faCircleDot,
	faCircleInfo,
	faCirclePlay,
	faCircleQuestion,
	faCode,
	faCodeBranch,
	faClock,
	faClone,
	faCloud,
	faCloudDownloadAlt,
	faCopy,
	faCut,
	faEdit,
	faEllipsisV,
	faEnvelope,
	faEye,
	faExpand,
	faExchangeAlt,
	faFile,
	faFileArchive,
	faFileArrowDown,
	faFileCode,
	faFileExport,
	faFileImport,
	faFilePdf,
	faFloppyDisk,
	faFolderOpen,
	faGear,
	faGears,
	faGift,
	faGraduationCap,
	faHardDrive,
	faHome,
	faHourglass,
	faImage,
	faInbox,
	faInfo,
	faKey,
	faLink,
	faListCheck,
	faLightbulb,
	faMagnifyingGlass,
	faMagnifyingGlassMinus,
	faMagnifyingGlassPlus,
	faMapSigns,
	faNetworkWired,
	faPause,
	faPauseCircle,
	faPen,
	faPlay,
	faPlayCircle,
	faPlug,
	faPlus,
	faPlusCircle,
	faPlusSquare,
	faQuestion,
	faRedo,
	faRotateLeft,
	faRss,
	faServer,
	faSignInAlt,
	faSlidersH,
	faSpinner,
	faStop,
	faSun,
	faSync,
	faSyncAlt,
	faTable,
	faTerminal,
	faThLarge,
	faTimes,
	faTrash,
	faTriangleExclamation,
	faUnlink,
	faUserCircle,
	faUserGroup,
	faUsers,
	faVideo,
	faStickyNote as faSolidStickyNote,
	faPencil,
	faCircleCheck,
} from '@fortawesome/free-solid-svg-icons';
import {
	faStickyNote,
} from '@fortawesome/free-regular-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

function addIcon(icon: any) { // tslint:disable-line:no-any
	library.add(icon as IconDefinition);
}

addIcon(faAngleDoubleLeft);
addIcon(faAngleDown);
addIcon(faAngleRight);
addIcon(faAngleUp);
addIcon(faArrowLeft);
addIcon(faArrowRight);
addIcon(faArrowUpRightFromSquare);
addIcon(faArrowsRotate);
addIcon(faAt);
addIcon(faBook);
addIcon(faBoxOpen);
addIcon(faBug);
addIcon(faCalendar);
addIcon(faCheck);
addIcon(faChevronLeft);
addIcon(faChevronRight);
addIcon(faChevronDown);
addIcon(faChevronUp);
addIcon(faCircleCheck);
addIcon(faCircleDot);
addIcon(faCircleInfo);
addIcon(faCirclePlay);
addIcon(faCircleQuestion);
addIcon(faCode);
addIcon(faCodeBranch);
addIcon(faClock);
addIcon(faClone);
addIcon(faCloud);
addIcon(faCloudDownloadAlt);
addIcon(faCopy);
addIcon(faCut);
addIcon(faEdit);
addIcon(faEllipsisV);
addIcon(faEnvelope);
addIcon(faEye);
addIcon(faExpand);
addIcon(faExchangeAlt);
addIcon(faFile);
addIcon(faFileArchive);
addIcon(faFileArrowDown);
addIcon(faFileCode);
addIcon(faFileExport);
addIcon(faFileImport);
addIcon(faFilePdf);
addIcon(faFloppyDisk);
addIcon(faFolderOpen);
addIcon(faGear);
addIcon(faGears);
addIcon(faGift);
addIcon(faGraduationCap);
addIcon(faHardDrive);
addIcon(faHome);
addIcon(faHourglass);
addIcon(faImage);
addIcon(faInbox);
addIcon(faInfo);
addIcon(faKey);
addIcon(faLink);
addIcon(faListCheck);
addIcon(faLightbulb);
addIcon(faMagnifyingGlass);
addIcon(faMagnifyingGlassMinus);
addIcon(faMagnifyingGlassPlus);
addIcon(faMapSigns);
addIcon(faNetworkWired);
addIcon(faPause);
addIcon(faPauseCircle);
addIcon(faPen);
addIcon(faPencil);
addIcon(faPlay);
addIcon(faPlayCircle);
addIcon(faPlug);
addIcon(faPlus);
addIcon(faPlusCircle);
addIcon(faPlusSquare);
addIcon(faQuestion);
addIcon(faRedo);
addIcon(faRotateLeft);
addIcon(faRss);
addIcon(faServer);
addIcon(faSignInAlt);
addIcon(faSlidersH);
addIcon(faSpinner);
addIcon(faSolidStickyNote);
addIcon(faStickyNote);
addIcon(faStop);
addIcon(faSun);
addIcon(faSync);
addIcon(faSyncAlt);
addIcon(faTable);
addIcon(faTerminal);
addIcon(faThLarge);
addIcon(faTimes);
addIcon(faTrash);
addIcon(faTriangleExclamation);
addIcon(faUnlink);
addIcon(faUserCircle);
addIcon(faUserGroup);
addIcon(faUsers);
addIcon(faVideo);

Vue.component('font-awesome-icon', FontAwesomeIcon);

